### ISSUE TITLE
Add desktop notifications and sounds

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/setTimeout#1]
The app should send a desktop notification and play a sound when the set timeout is completed.

**Comment by Adroit11** [comment]
Did like to try this, and get my fingers busy with the desktop notification and sound

**Comment by flaredragon** [comment]
I've worked on this please review PR.Change Sound as per your choice.

**Comment by anshumanv** [comment]
@Adroit11 @flaredragon has already fixed it, thanks for showing interest here, please consider doing any other changes/updates in this project if you like.

**Comment by anshumanv** [comment]
Btw @flaredragon i really liked the notification song that you sent !
